---
#Play: Setup LAMP server
- name: setup LAMP server
  hosts: centos
  tasks:

    - 
      name: setup LAMP server
      yum: 
        name: httpd
        state: "present"
      command: 
        cmd: echo "systemctl status httpd"
      register: result

    - name: show result tasks on screen 
      debug: var=result.stdout_lines
