---
#Play: Setup LAMP server
- name: setup LAMP server
  hosts: centos
  tasks:

    - name: setup LAMP server
      yum: 
        name: {{packages}}
        state: present
      vars:
        packages:
          - httpd
          - mysql
          - php
      
    
    - name : check status
      command: systemctl status httpd
      register: result

    - name: show result tasks on screen 
      debug: var=result.stdout_lines
